FROM golang:alpine

RUN apk add --no-cache \
  docker-cli \
  postgresql-client \
  docker

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o worker cmd/worker/main.go

CMD ["./worker"]
